version: "3"
networks:
  leo_network:
    external: true

services:
  leo:
    build:
      context: leo-rover
      dockerfile: Dockerfile
    container_name: leo
    image: ros-leo
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    #network_mode: "host"
    # No need to expose ports, inside the leo_network the bridge can see container port 11311
    #ports:
    #  - "11311:11311"
    networks:
      - leo_network
    environment:
      - "DISPLAY"
      # If assigning IP, make shure is the same as in leo_network
    #  - "ROS_IP=172.19.0.3"
      - "ROS_HOSTNAME=leo"
      - "ROS_MASTER_URI=http://localhost:11311"
    restart: always


  bridge:
    image: ros:foxy-ros1-bridge
    environment:
      # If assigning IP, make shure is the same as in leo_network
    #  - "ROS_IP=172.19.0.4"
      - "ROS_HOSTNAME=bridge"
      - "ROS_MASTER_URI=http://leo:11311"
    networks:
      - leo_network
    depends_on:
      - leo
    ports:
      # Open DDS standard ports for Domain ID 0 in host
      # Read in https://docs.ros.org/en/galactic/Concepts/About-Domain-ID.html
      - "7400:7400/udp"
      - "7401:7401/udp"
      - "7410:7410/udp"
      - "7411:7411/udp"
    command: ros2 run ros1_bridge dynamic_bridge