version: "3"
services:

  leo:
    build:
      context: leo-rover
      dockerfile: Dockerfile
    container_name: leo
    image: ros-leo
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    #network_mode: "host"
    environment:
     - "DISPLAY"
     - "ROS_IP=172.19.0.3"
     - "ROS_HOSTNAME=leo"
     - "ROS_MASTER_URI=http://localhost:11311"
    restart: always


  bridge:
    build:
      context: rosbridge
      dockerfile: Dockerfile
    #container_name: ros-bridge
    image: ros-bridge
    environment:
     - "ROS_HOSTNAME=bridge"
     - "ROS_IP=172.19.0.4"
     - "ROS_MASTER_URI=http://leo:11311"
    depends_on:
     - leo
    #network_mode: "host"
    ports:
      - "9090:9090"
    command:
      - ros2 run ros1_bridge dynamic_bridge
    restart: always
